### ISSUE TITLE
Add an additional boolean output denoting if there is no diff

### ISSUE THREAD

**Issue by dan-j** [loveholidays/gitops-action-kustomize-compare#1]
Great project! Just starting playing with it and love it 😃 

I'm trying to use an `if` on my subsequent comment step to print a different message if the diff is empty, since otherwise you just get an empty code-block in the PR comments.

I've tried the following expressions, and none work:

```yaml
if: ${{ steps.kustomize-diff.outputs.diff != '' }}
if: ${{ steps.kustomize-diff.outputs.diff != '``` diff%0A%0A```' }}
if: ${{ steps.kustomize-diff.outputs.diff != '``` diff\n\n```' }}
```

How about adding an additional output, `is_empty` which is `true/false` dependent on if the diff is empty or not.

I don't mind contributing a PR if a maintainer agrees.
